server:
  port: 8081

spring:
  application:
    name: USER-SERVICE   # 👈 microservice nu naam (Eureka ma aa naam thi register thase)

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Trivedisahil91
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}   # 👈 unique ID for registration
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
