#spring.application.name=HotelService
server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: Trivedisahil_91

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}   # 👈 unique ID for registration
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



